#!/bin/bash
# install nfs server 

set -e

# setup nfs dir
NFS_DIR=/home/huhu/

sudo apt-get install -f -y nfs-kernel-server

# export nfs dir
# echo ${NFS_DIR} '*(rw,sync,no_root_squash,no_subtree_check)' | sudo tee /etc/exports
sudo sh -c "echo '${NFS_DIR} *(rw,sync,no_root_squash,no_subtree_check)' > /etc/exports"

# nfs is rpc process, port needed to mapped
sudo service rpcbind restart

# restart server
sudo service nfs-kernel-server restart
showmount -e

echo "Done!"
